Runner 9
TeammFive/Runner pull request #2
Opened 2022-08-20 09:54 UTC by veniameen

Runner 3 + Обновлен дизайн сайта

2022-08-20 10:19 UTC, loosq commented on package.json
> +        "@svgr/webpack": "^6.3.1",
предлагаю зависимости ставить без крышки (^)

2022-08-20 10:19 UTC, loosq commented on src/components/base/Avatar/Avatar.tsx
> +                    .catch(() => {
`catch((e) => {
    console.error(e.message);
    setLoading(false);
}`

2022-08-20 10:19 UTC, loosq commented on src/components/pages/Leaderboard/Leaderboard.scss
> +                background-color: rgb(0 168 189);
предлагаю цвета указывать в hex

2022-08-20 10:19 UTC, loosq commented on src/components/pages/Login/Login.tsx
> +                .catch(() => {
тоже бы ошибку отловить

2022-08-21 12:48 UTC, AMorozov-web requested changes
Работа супер, отписал по мелким моментам, если что дергай - помогу

2022-08-21 12:48 UTC, AMorozov-web commented on package.json
> +        "redux-typescript": "1.2.1",
Вот это уже давно устарело - удали и установи @types/react-redux

2022-08-21 12:48 UTC, AMorozov-web commented on src/api/AuthAPI.ts
> +export default {
Лучше именованный экспорт

2022-08-21 12:48 UTC, AMorozov-web commented on src/api/UsersAPI.ts
> +export default {
Лучше именованный экспорт

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/base/Avatar/Avatar.tsx
> +    const inputAvatar = useRef<any>();
Укажи тип

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/base/Avatar/Avatar.tsx
> +    const dispatch = useDispatch<any>();
Укажи тип

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/complex/Form/Form.tsx
> +    custom?: any
Укажи тип

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/complex/Navigation/Navigation.scss
> +                        height: 0.3vw;
Относительные величины лучше в процентах - более очевидно

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/complex/Navigation/Navigation.scss
> +                        bottom: -0.7vw;
Тоже самое

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/complex/Navigation/Navigation.scss
> +        background: #f7f7f7;
Цвета -  в общий каталог и тяни оттуда

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/complex/Navigation/Navigation.scss
> +        border: 1px solid #f0f0f0;
Цвета - в общий каталог и тяни оттуда

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/complex/Navigation/Navigation.scss
> +        color: #fff;
Цвета - в общий каталог и тяни оттуда

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/complex/Navigation/Navigation.scss
> +        background: #ebebeb;
Цвета - в общий каталог и тяни оттуда

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/complex/Navigation/Navigation.tsx
> +    const dispatch = useDispatch<any>();
Укажи тип

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/pages/Forum/Forum.tsx
>  export const Forum: React.FC<unknown> = React.memo(() => (
У компонента не пропсов - memo бесполезно

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/pages/Login/Login.tsx
> +    const dispatch = useDispatch<any>();
Укажи тип

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/pages/Login/Login.tsx
>      });
Схемы лучше держать вне компонента

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/pages/Registration/Registration.tsx
> +    const dispatch = useDispatch<any>();
Укажи тип

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/pages/Settings/Settings.tsx
> +export const Settings: React.FC<UserProfileData | any> = React.memo(() => {
Убери any

2022-08-21 12:48 UTC, AMorozov-web commented on src/components/pages/Settings/Settings.tsx
> +    const dispatch = useDispatch<any>();
Укажи тип

2022-08-21 12:48 UTC, AMorozov-web commented on src/slices/base.ts
> +  await AuthService.logout();
Здесь лучше тоже обработать ошибку, поскольку и тут запрос может не дойти

2022-08-21 12:48 UTC, AMorozov-web commented on src/slices/base.ts
> +});
Сделай через [builder.addCase](https://redux-toolkit.js.org/usage/usage-with-typescript#type-safety-with-extrareducers) - это избавит тебя от any

2022-08-23 20:17 UTC, loosq approved these changes

2022-09-04 08:56 UTC, merged